use_frameworks!

platform :ios, '10.0'

source 'https://github.com/guxingjian/SFPodB.git'

target 'SFPodA_Example' do
  pod 'SFPodA', :path => '../'

  target 'SFPodA_Tests' do
    inherit! :search_paths

    
  end
end
